### register user
POST http://localhost:8080/v1/auth/registration
Content-Type: application/json

{
  "email": "test@asd.com",
  "password": "qwerty",
  "confirm_password": "qwerty"
}

### login user
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "email": "test@asd.com",
  "password": "qwerty"
}

### about me
GET http://localhost:8080/v1/auth/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

### refresh token
POST http://localhost:8080/v1/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}