### register user
POST http://localhost:8080/v1/auth/registration
accept: application/json
Content-Type: application/json

{
  "email": "asd@asd.com",
  "password": "qwerty",
  "confirmPassword": "qwerty"
}