### test endpoint
POST http://localhost:8080/v1/auth/test
accept: application/json
Content-Type: application/json

{
  "email": "111@asd.com",
  "password": "qwerty",
  "confirmPassword": "qwerty"
}

### register user
POST http://localhost:8080/v1/auth/registration
Content-Type: application/json

{
  "email": "111@asd.com",
  "password": "qwerty",
  "confirmPassword": "qwerty"
}

### login user
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "email": "111@asd.com",
  "password": "qwerty",
  "confirmPassword": "qwerty"
}