server:
  port: 8080
spring:
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.authUrl}/realms/${keycloak.realm}
jwt:
  jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  enabled: true
  realm: appauth
  clientId: app-auth-client-id
  clientSecret: XCbcG922tAUdZq0uux5hwhlQzsUeXyk4
  authUrl: http://localhost:9005
logging:
  level:
    root: info
