server:
  port: 8080
spring:
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9005/realms/${keycloak.realm}
jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: ${keycloak.clientId}
  jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  realm: appauth
  clientId: app-auth-client-id
  clientSecret: XCbcG922tAUdZq0uux5hwhlQzsUeXyk4
  authUrl: http://localhost:9005
url-frontend-guest: http://localhost
logging:
  level:
    root: info
